app/__init__.py
from flask import Flask, render_template, url_for, send_file

app = Flask(__name__)

app.config.from_object('app.config.DevelopmentConfig')

from app.main.views import main_blueprint

app.register_blueprint(main_blueprint)

app/main/views.py
from flask import render_template, send_file, url_for, Blueprint, redirect



main_blueprint = Blueprint('main', __name__,)

@main_blueprint.route('/', methods=['GET', 'POST'])
def home():
	return render_template('index.html')

@main_blueprint.route('/faq', methods=['GET', 'POST'])
def faq():
	return render_template('faq.html', methods=['GET'])

@main_blueprint.route('/specs', methods=['GET', 'POST'])
def specs():
	return render_template('specs.html', methods=['GET'])

@main_blueprint.route('/merchants', methods=['GET', 'POST'])
def merchants():
	return render_template('merchants.html', methods=['GET'])

@main_blueprint.route('/extras', methods=['GET', 'POST'])
def extras():
	return render_template('extras.html', methods=['GET'])

@main_blueprint.route('/logic.phm', methods=['GET', 'POST'])
def logic():
	return render_template('logic.phm.html', methods=['GET'])



@main_blueprint.route('/woodcoin.pdf/', )
def woodcoin():
    
    return send_file('/home/robert/woodcoin.org/app/static/woodcoin.pdf', attachment_filename='woocoin.pdf')

app/templates/_base.html
<!-- Except where illegal, all website code is original (c) 2015 www.phm.link and
licensed under Mozilla Public License 2.0. Certain parts and files are not original nor sublicensed here.
They are noted as such. More on the license http://mozilla.org/MPL - LICENSE DOES NOT APPLY WHERE IT CONFLICTS. -->

<!DOCTYPE html>
  
<html lang="en">

<head>
  <title>Woodcoin: Sustainable. Digital. Cash. </title>
  <meta name="description" content="" />
  <meta name="keywords" content="woodcoin, cryptocurrency, bitcoin, funkenstein, moonpunter" />
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <link href="{{url_for('static', filename='css/main.css')}}" rel="stylesheet" media="screen" />
  {% block css %}{% endblock %}
</head>
<body>
	<!-- child template -->
    {% block content %}{% endblock %}

    {% include "side.html" %}
</body>

</html>

app/templates/bounties.html
<!-- Except where illegal, all website code is original (c) 2015 www.phm.link and
licensed under Mozilla Public License 2.0. Certain parts and files are not original nor sublicensed here.
They are noted as such. More on the license http://mozilla.org/MPL - LICENSE DOES NOT APPLY WHERE IT CONFLICTS. -->
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Woodcoin: Help the Forest, Earn LOGs</title>
  <meta name="description" content="" /> 
  <meta name="keywords" content="woodcoin, cryptocurrency, bitcoin, funkenstein, moonpunter" />
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />

  <link rel="stylesheet" type="text/css" href="css/main.css" />
</head>
<body>
   
   <div id="forest" class="fst"><div style="height: 45px;"></div>
    <h1 class="fsth">Bounty List</h1>
    <h2 class="fsth"><a href="faq.html">FAQ</a> &#8486; <a href="specs.html">Specifications</a> &#8486; <a href="woodcoin.pdf">Whitepaper</a> &#8486; <a href="http://logaddress.org/index.html">Paper Notes</a></h2>
   <p>Coming soon. Write to &#102;&#117;&#110;&#107;&#101;&#110;&#115;&#116;&#101;&#105;&#110;&#064;&#119;&#111;&#111;&#100;&#099;&#111;&#105;&#110;&#046;&#111;&#114;&#103; if you have a suggestion.</p>
   <p><br/></p>
   <p><br/></p>
    <footer>
  Many icons designed by <a href="http://freepik.com" target="_blank">Freepik</a>. 
 </footer> 
   
   </div>
  <div id="overhead">
  <div align="center"><a href="index.html"><img src="img/etc/forest-overhead.png" height="75px" width="75px" style="margin-right: 75px;"></a></div>
  <ul style="list-style-type: none;" class="oh">
  <li><img src="img/icns/pools.png"> Pools <span>[<a href="http://wood.suprnova.cc/" target="_blank">1</a>][<a href="http://coinspool.cu.cc/info_woodcoin" target="_blank">2</a>]&nbsp;</span> <br/></li>
  <li><img src="img/icns/exchanges.png"> Exchanges <span>[<a href="https://c-cex.com/?p=log-btc" target="_blank">1</a>]&nbsp;</span> </br></li>
  <li><img src="img/icns/ledgers.png"> Public Ledger <span>[<a href="http://altcoinguys.blockexperts.com/log" target="_blank">1</a>][<a href="http://www.multifaucet.tk/index.php?blockexplorer=LOG" target="_blank">2</a>]</li>
  <li><img src="img/icns/faucets.png"> Free Coin <span>[<a href="http://www.faucetrotator.uni.me/woodcoin/" target="_blank">1</a>][<a href="http://www.multifaucet.tk/index.php?faucet=LOG" target="_blank">2</a>]&nbsp;</span><br/></li>
  <li><img src="img/icns/bounties.png"> Earn Coin <span>[<a href="bounties.html"><b>Bounties</b></a>]</span></li>
<li><img src="img/icns/community.png"> Khaz <span>[<a href="http://woodcutting.club" target="_blank">1</a>][<a href="https://kiwiirc.com/client/irc.freenode.net/#woodcoin" target="_blank">2</a>][<a href="https://bitcointalk.org/index.php?topic=831003.0" target="_blank">3</a>][<a href="http://fre.erepublic.party/cgi-bin/mailman/listinfo/woodcoin" target="_blank">4</a>]</span><br/></li>  <li><img src="img/icns/downloads.png"> Downloads <span>[<a href="official.html">Official</a>] [<a href="unofficial.html">Other</a>]</span></li>
  <li><img src="img/icns/code.png"> Code <span>[<a href="https://github.com/funkshelper/woodcoin/" target="_blank">Github</a>] [Fosshub] [<b><a href="http://github.com/paulmadore/woodcoin-dot-org" target="_blank">.org</a></b>]</span></li>
  <li><img src="img/icns/media.png"> Media <span>[<a href="http://frass.woodcoin.org" target="_blank">FRASS</a>] </span></li>
  <li><img src="img/icns/etc.png"> Et Cetera <span>[<a href="merchants.html">Merchants</a>] [<a href="extras.html">Swag</a>] [<a href="logic.phm.html">OpenTTD Map</a>]</span></li>
  </ul>

  </div>
 </div>

        
</body>
</html>
 

app/templates/extras.html
{% extends "_base.html" %}
{% block content %}
   
   <div id="forest" class="fst"><div style="height: 45px;"></div>
    <h1 class="fsth">Stuff That Makes Us Cooler</h1>
    <h2 class="fsth"><a href="{{ url_for('main.faq') }}">FAQ</a> &#8486; <a href="{{ url_for('main.specs') }}">Specifications</a> &#8486; <a href="{{ url_for('main.woodcoin') }}">Whitepaper</a>  &#8486; <a href="http://logaddress.org/index.html">Paper Notes</a></h2>
    <h2>Eye Candy</h2>
    <p>Send any prospective eye candy to &#102;&#117;&#110;&#107;&#101;&#110;&#115;&#116;&#101;&#105;&#110;&#064;&#119;&#111;&#111;&#100;&#099;&#111;&#105;&#110;&#046;&#111;&#114;&#103;. Click on an image to open it in a new tab, full resolution.</p>
    <div align="center">
        <a href="{{ url_for('static', filename='img/etc/woodcoin-moon.phm.png') }}" target="_blank"><img src="{{ url_for('static', filename='img/etc/woodcoin-moon.phm.png') }}" width="95%" alt="click for high-resolution" class="swag"></a><br/>
        <span class="caption" style="font-size: larger;">Future logging.</span> <span class="contr">Free under MPL 2.0, by <a href="http://phm.link" target="_blank">phm</a></span>
        <a href="{{ url_for('static', filename='img/etc/woodcoin-bigger-concept.phm.png') }}" target="_blank"><img src="{{ url_for('static', filename='img/etc/woodcoin-bigger-concept.phm.png') }}" width="95%" alt="click for high-resolution" class="swag"></a><br/>
        <span class="caption" style="font-size: larger;">Just another wooden nickel?</span> <span class="contr">Free under MPL 2.0, by <a href="http://phm.link" target="_blank">phm</a></span>
        <a href="{{ url_for('static', filename='img/etc/silver-electricity-history-woodcoin-rising-above.phm.png') }}" target="_blank"><img src="{{ url_for('static', filename='img/etc/silver-electricity-history-woodcoin-rising-above.phm.png') }}" width="95%" alt="click for high-resolution" class="swag"></a><br/>
        <span class="caption" style="font-size: larger;">Woodcoin looks over it all.</span> <span class="contr">Free under MPL 2.0, by <a href="http://phm.link" target="_blank">phm</a></span>
        
        
        
    </div>
    <p></p>
    <p>Don't forget to check out the <a href="logic.phm.html">OpenTTD scenario</a> and our <a href="official.html">vanity address generator</a>.</p>
    
   <!--p>There are some online servers currently running the scenario 24 hours a day.</p-->
   
    <footer>
  Many icons designed by <a href="http://freepik.com" target="_blank">Freepik</a>. 
 </footer> 
   
   </div>
 {% endblock %}
 

app/templates/faq.html
{% extends "_base.html" %}
{% block content %}
   
   <div id="forest" class="fst"><div style="height: 45px;"></div>
        <h1 class="fsth">Sustainability is the Watch Word</h1>
        <h2 class="fsth"><a href="{{ url_for('main.faq') }}"><em>FAQ</em></a> &#8486; <a href="{{ url_for('main.specs') }}">Specifications</a> &#8486; <a href="{{ url_for('main.woodcoin') }}">Whitepaper</a> &#8486; <a href="http://logaddress.org/index.html">Paper Notes</a></h2>
        <h3 class="faq">How do I start chopping?</h3>
        <p>If you are using <span class="capfaq">woodcoind</span> you need to issue the command <span class="captfaq">woodcoind setgenerate true</span>. If you are using <span class="capfaq">woodcoin-qt</span>, you need to navigate as follows:<br/>
        <ul style="width: 425px; color: #728188; font-family: serif;">
          <li style="list-style-type: circle;"><span class="captfaq">Help ==>  Debug Window ==> Console Tab.</span></li>
          <li style="list-style-type: circle;">Then in the console type the command <span class="captfaq">setgenerate true</span> and press <span class="captfaq">Enter</span>.</li>
          <li style="list-style-type: circle;">To check your woodcutting progress, go to the same console and type <span class="captfaq">getmininginfo.</span></li>
        </ul>
        
        <h3 class="faq">I'm behind a checkpoint and alerts aren't working. What&rsquo;s up?</h3>
        <p>The philosophy of woodcoin is complete decentralization.  Checkpoints and alerts are not used.</p>
        
        <h3 class="faq">How can I contribute?</h3>
        <p>Start chopping wood!  By chopping wood and collecting LOGs, you are helping secure the Woodcoin network. By using LOGs as tokens of exchange, you are helping to spread the word about woodcoin.</p>

    <p>The code which runs woodcoin will always be open source.   Take a look and submit your changes on github.  There are many other tools still missing from the woodcutting arsenal and new ideas of all sorts are appreciated.  If you can&rsquo;t code it up yourself, tell us about it on one of the forums and maybe we can do it for you.</p>
        
        <footer>
      Many icons designed by <a href="http://freepik.com" target="_blank">Freepik</a>. 
     </footer> 
   </div>
  {% endblock %}
 

app/templates/index.html
{% extends "_base.html" %}
{% block content %}
  
   
   <div id="forest" class="fst"><div style="height: 45px;"></div>
      <h1 class="fsth">&amp; Wood Enough For All</h1>
      <h2 class="fsth"><a href="{{ url_for('main.faq') }}">FAQ</a> &#8486; <a href="{{ url_for('main.specs') }}">Specifications</a> &#8486; <a href="{{ url_for('main.woodcoin') }}">Whitepaper</a> &#8486; <a href="http://logaddress.org/index.html">Paper Notes</a></h2>
      <p>Woodcoin is a public digital currency which uses Pure Skein. Its unit of exchange is LOG. It is similar to other cryptocurrencies, but has key differences. Woodcoin was invented by Funkenstein the Dwarf in October 2014. Old site <a href="http://archive.woodcoin.org">here</a>.  <a href="http://archive.woodcoin.org/index.php/category/chinese/">中文</a></p>
      <br/>
      <ul>
      <li>Woodcoin&rsquo;s harmonic distribution is designed to more closely model renewable resources than nonrenewable ones. This means that while it is always better to chop LOGs today, there will still be incentive to chop tomorrow.</li>
      <li>The logarithmic money supply curve is designed for stability and longevity,  with the longest reward schedule of any other cryptocurrency.</li>
      <li>It also features novel coin design in proof of work function (Pure Skein) and in digital signature keypairs (X9_62_prime256v1).</li>
      </ul>
      <br/>
      <div align="center"><img src="{{ url_for('static', filename='img/etc/woodcoin-v-bitcoin-distribution.png') }}" height="270" width="450" alt="Here is a plot of the Daily rewards comparing BTC released per day to LOG released per day for the next  45 years.  For more on the economics of a logarithmically increasing money supply read the whitepaper."><br/></div><span class="caption">Here is a plot of the Daily rewards comparing BTC released per day to LOG released per day for the next  45 years.  For more on the economics of a logarithmically increasing money supply, read the <a href="woodcoin.pdf">whitepaper</a>.</span>
     
      <footer>
        Many icons designed by <a href="http://freepik.com" target="_blank">Freepik</a>. 
     </footer> 
     
   </div>
  
{% endblock %}
 

app/templates/logic.phm.html
{% extends "_base.html" %}
{% block content %}
   
   <div id="forest" class="fst"><div style="height: 45px;"></div>
    <h1 class="fsth">Sustainability is the Watch Word</h1>
    <h2 class="fsth"><a href="{{ url_for('main.faq') }}">FAQ</a> &#8486; <a href="{{ url_for('main.specs') }}">Specifications</a> &#8486; <a href="{{ url_for('main.woodcoin') }}">Whitepaper</a>  &#8486; <a href="http://logaddress.org/index.html">Paper Notes</a></h2>
    <p>The Woodcoin team presents an <a href="http://openttd.org" target="_blank">OpenTTD</a> scenario which demonstrates the superiority of sustainable resources versus limited ones. Over the course of 100 years, beginning in 2008, two or more companies can play this map. It is not a guarenteed win for the chopper versus the miner.  </p>
    <p>The most current version of the scenario is available <a href="http://github.com/paulmadore/woodcoin/openttd-scn" target="_blank">here</a>. Below are some screenshots. You may submit a pull request with new scenarios, screenshots, and so on, if you like.</p>
    
   <!--p>There are some online servers currently running the scenario 24 hours a day.</p-->
   
    <footer>
  Many icons designed by <a href="http://freepik.com" target="_blank">Freepik</a>. 
 </footer> 
   
   </div>
   {% endblock %}
 

app/templates/merchants.html
{% extends "_base.html" %}
{% block content %}
  
   
   <div id="forest" class="fst"><div style="height: 45px;"></div>
    <h1 class="fsth">Where to Spend Woodcoins</h1>
    <h2 class="fsth"><a href="{{ url_for('main.faq') }}">FAQ</a> &#8486; <a href="{{ url_for('main.specs') }}">Specifications</a> &#8486; <a href="{{ url_for('main.woodcoin') }}">Whitepaper</a> &#8486; <a href="http://logaddress.org/index.html">Paper Notes</a></h2>
    <p>The following merchants welcome your LOGs in exchange for goods and services.</p>
    <br/><br/>
    <ul>
    <li><a href="http://erepublic.party/hosting.html">eRepublic Web Hosting Services</a></li>
    </ul>
   <p><b>If you are a merchant who would like help accepting Woodcoin,</b> please do not hesitate to contact the Woodcoin mailing list, &#119;&#111;&#111;&#100;&#099;&#111;&#105;&#110;&#064;&#102;&#114;&#101;&#046;&#101;&#114;&#101;&#112;&#117;&#098;&#108;&#105;&#099;&#046;&#112;&#097;&#114;&#116;&#121;. Contact &#112;&#104;&#109;&#064;&#119;&#111;&#111;&#100;&#099;&#111;&#105;&#110;&#046;&#111;&#114;&#103; if you are a merchant already accepting LOGs and would like to be added to this list. </p>
   
    <footer>
  Many icons designed by <a href="http://freepik.com" target="_blank">Freepik</a>. 
 </footer> 
   
   </div>
  {% endblock %}
 

app/templates/side.html
<div id="overhead">
    <div align="center"><img src="{{ url_for('static', filename='img/etc/forest-overhead.png') }}" height="75px" width="75px" style="margin-right: 75px;"></div>
    <ul style="list-style-type: none;" class="oh">
    <li><img src="{{ url_for('static', filename='img/icns/pools.png') }}"> Pools <span>[<a href="http://wood.suprnova.cc/" target="_blank">1</a>][<a href="http://coinspool.cu.cc/info_woodcoin" target="_blank">2</a>]&nbsp;</span> <br/></li>
    <li><img src="{{ url_for('static', filename='img/icns/exchanges.png') }}"> Exchanges <span>[<a href="https://c-cex.com/?p=log-btc" target="_blank">1</a>]&nbsp;</span> </br></li>
    <li><img src="{{ url_for('static', filename='img/icns/ledgers.png') }}"> Public Ledger <span>[<a href="http://altcoinguys.blockexperts.com/log" target="_blank">1</a>][<a href="http://www.multifaucet.tk/index.php?blockexplorer=LOG" target="_blank">2</a>]</li>
    <li><img src="{{ url_for('static', filename='img/icns/faucets.png') }}"> Free Coin <span>[<a href="http://www.faucetrotator.uni.me/woodcoin/" target="_blank">1</a>][<a href="http://www.multifaucet.tk/index.php?faucet=LOG" target="_blank">2</a>]&nbsp;</span><br/></li>
    <li><img src="{{ url_for('static', filename='img/icns/bounties.png') }}"> Earn Coin <span>[<a href="bounties.html">Bounties</a>]</span></li>
  <li><img src="{{ url_for('static', filename='img/icns/community.png') }}"> Khaz <span>[<a href="http://woodcutting.club" target="_blank">1</a>][<a href="https://kiwiirc.com/client/irc.freenode.net/#woodcoin" target="_blank">2</a>][<a href="https://bitcointalk.org/index.php?topic=831003.0" target="_blank">3</a>][<a href="http://fre.erepublic.party/cgi-bin/mailman/listinfo/woodcoin" target="_blank">4</a>]</span><br/></li>  <li><img src="{{ url_for('static', filename='img/icns/downloads.png') }}"> Downloads <span>[<a href="official.html">Official</a>] [<a href="unofficial.html">Other</a>]</span></li>
    <li><img src="{{ url_for('static', filename='img/icns/code.png') }}"> Code <span>[<a href="https://github.com/funkshelper/woodcoin/" target="_blank">Github</a>] [Fosshub] [<b><a href="http://github.com/paulmadore/woodcoin-dot-org" target="_blank">.org</a></b>]</span></li>
    <li><img src="{{ url_for('static', filename='img/icns/media.png') }}"> Media <span>[<a href="http://frass.woodcoin.org" target="_blank">FRASS</a>] </span></li>
    <li><img src="{{ url_for('static', filename='img/icns/etc.png') }}"> Et Cetera <span>[<a href="{{ url_for('main.merchants') }}">Merchants</a>] [<a href="{{ url_for('main.extras') }}">Swag</a>] [<a href="{{ url_for('main.logic') }}">OpenTTD Map</a>]</span></li>
    </ul>

    </div>
 </div>

app/templates/specs.html
{% extends "_base.html" %}
{% block content %}
   
   <div id="forest" class="fst"><div style="height: 45px;"></div>
    <h1 class="fsth">Stuff That Makes Us Cooler</h1>
    <h2 class="fsth"><a href="{{ url_for('main.faq') }}">FAQ</a> &#8486; <a href="{{ url_for('main.specs') }}"><em>Specifications</em></a> &#8486; <a href="{{ url_for('main.woodcoin') }}">Whitepaper</a> &#8486; <a href="http://logaddress.org/index.html">Paper Notes</a></h2>
    <h2>Technical Details</h2>
    <p>Woodcoin is a public cryptocurrency like <a href="http://en.bitcoin.it" target="_blank">Bitcoin</a>.  There are three major changes, with design considerations listed here:</p>
<ol class="spec" style="list-style-type: decimal;"><li> Proof of Work algorithm:  Double Skein<br/><br/>
<span class="capspec">This is the first consensus network built solely with the <a href="https://en.wikipedia.org/wiki/Skein_%28hash_function%29" target="_blank">skein hash function</a>.  Read more about Skein <a href="http://www.skein-hash.info/about" target="_blank">here</a>.  We hope to encourage further use and testing of the Skein family with this coin.</span></li>

<li>Elliptic Curve for Digital Signatures: X9_62_prime256v1.<br/><br/>
<span class="capspec">To sign transactions and create public and private addresses we use the elliptic curve digital signature algorithm ECDSA just like bitcoin.  However we use a different curve as a basis to do so.  This curve is perhaps the most used in the financial industry.  Some people think it is better.  We like to encourage cryptographic diversity.</span></li>

<li>Logarithmic Coin Release<br/><br/>
Woodcoin is the first coin to use a logarithmic coin release. The woodcutting reward is continually adjusted according to the harmonic series. From /src/main.cpp:</li>
<blockquote>
int64 static GetBlockValue(int nHeight, int64 nFees) {<br/>
int64 nSubsidy = 1000000 * COIN;<br/>
if (nHeight<100) return 1*COIN;<br/>
else return nSubsidy/nHeight + nFees;<br/>
}<br/></blockquote>

<p>This leads to a total money supply <span class="capspec">S</span> which increases logarithmically in block height <span class="capspec">n</span>:</p>
<blockquote>
S = 1000000* ( log n + gamma )   –  forest<br/>
log = natural logarithm<br/>
gamma = euler-mascheroni constant<br/>
forest  =  5187377.51763962 </blockquote>

<p>Unlike Bitcoin and most other cryptocurrencies, the reward will never drop to zero and will smoothly decrease.  (Techinically it is scheduled to reach zero when the reward drops to under 1 satoshi but that isn’t for about 350 million years)  Here is a plot of the woodcutting reward per day, compared to bitcoin, for the next 50 years or so:</p>

<div align="center"><img src="{{ url_for('static', filename='img/etc/woodcoin-v-bitcoin-distribution.png') }}" height="270" width="450" alt="Here is a plot of the Daily rewards comparing BTC released per day to LOG released per day for the next  45 years.  For more on the economics of a logarithmically increasing money supply read the whitepaper."><br/></div>

<h3>Other technical details of Woodcoin:</h3>

<ul><li>Port: 8338</li>
<li>Testnet: 18338</li>
<li>RPC: 9338</li>
<li>RPC Testnet: 19338</li>
<li>Speed: 2 min. blocks</li>
<li>Difficulty: 1 hr. adjust</li></ul>

<h3>Heritage:</h3>

<p>Notable continued coin heritage: <a href="http://en.bitcoin.it" target="_blank">Bitcoin</a>, <a href="https://github.com/litecoin-project/litecoin" target="_blank">Litecoin</a>, <a href="http://www.quarkcoins.com/" target="_blank">Quarkcoin</a>.</p>

<p>Depricated heritage (release version): <a href="http://www.cthulhu.tk/" target="_blank">Cthulu&rsquo;s Offerings</a>, Foocoin/SmallChange.</p>
   
    <footer>
  Many icons designed by <a href="http://freepik.com" target="_blank">Freepik</a>. 
 </footer> 
   
   </div>
{% endblock %}
 